"""Casper FFG honest baseline scenarios.

SCENARIOS is the list of (n, variant) scenarios run by
src/output/baseline.py and asserted by
tests/integration/test_pos_baseline.py. run_scenario(meta) builds the
FFG stack at meta.n with the meta.variant stake distribution, runs to
meta.t_max, and returns the (records, result, meta) triple the unified
CSV writer consumes.

Design spec: docs/superpowers/specs/2026-05-28-t40-output-format-design.md
"""
from __future__ import annotations

import math
from types import MappingProxyType

from common import run_to_completion
from config.factory import build_run
from config.schema import Config, SeedsConfig
from event_log import EventRecord
from network import DelayDist, Phase
from output.schema import ScenarioMeta
from scheduler import RunResult
from workload import WorkloadConfig, generate_batches

from .node import CasperNode


_MINIMAL_DELAY = (Phase(0.0, math.inf, DelayDist("constant", {"delay": 1e-9})),)
_T_MAX = 20.0
_SLOT_DURATION = 1.0
_SLOTS_PER_EPOCH = 2

# T41 offered transaction load. Mirrors the ScenarioMeta workload-axis
# defaults so the FFG reducer (src/pos/summarise.py) regenerates the
# byte-identical batch stream from meta alone.
_ARRIVAL_PROCESS = "poisson"
_OFFERED_RATE = 100.0
_TX_BYTES = 512
_CONFLICT_RATE = 0.0
# One batch per proposal opportunity (slot). Slots run 1.._T_MAX/_SLOT_DURATION;
# +2 headroom covers the genesis slot 0 and any boundary slot the timer arms.
_N_OPPORTUNITIES = math.ceil(_T_MAX / _SLOT_DURATION) + 2


def _uniform(n: int) -> dict[int, float]:
    return {i: 3.0 for i in range(n)}


def _nonuniform_n4() -> dict[int, float]:
    return {0: 5.0, 1: 4.0, 2: 2.0, 3: 1.0}


def _stake_table(n: int, variant: str | None) -> dict[int, float]:
    if variant == "nonuniform":
        assert n == 4, "nonuniform is only defined at n=4 today"
        return _nonuniform_n4()
    return _uniform(n)


def _config(n: int, variant: str | None) -> Config:
    return Config(
        n=n,
        t_max=_T_MAX,
        seeds=SeedsConfig(n_runs=1),
        network=_MINIMAL_DELAY,
        adversary=MappingProxyType({}),
        protocol_knobs=MappingProxyType({}),
        workload=MappingProxyType({}),
    )


def _factory(n: int, variant: str | None):
    stake_table = _stake_table(n, variant)

    def make(node_id: int, global_seed: int) -> CasperNode:
        # Build the slot-indexed batch stream once per run from the run's
        # global_seed. Every node holds the IDENTICAL list; only the
        # per-slot proposer reads workload[slot]. The same (config, seed)
        # is regenerated by the FFG reducer, so the streams agree.
        batches = generate_batches(
            WorkloadConfig(_ARRIVAL_PROCESS, _OFFERED_RATE,
                           _TX_BYTES, _CONFLICT_RATE),
            global_seed,
            n_opportunities=_N_OPPORTUNITIES,
            interval=_SLOT_DURATION,
        )
        return CasperNode(
            node_id=node_id, weight=stake_table[node_id], endpoint=None,
            global_seed=global_seed, n=n, stake_table=stake_table,
            slot_duration=_SLOT_DURATION, slots_per_epoch=_SLOTS_PER_EPOCH,
            workload=[b for b in batches],
        )
    return make


# T41 scaling sweep. Uniform stake at n in {4,7,10,16,25} x seed in
# range(20) = 100 metas, plus the retained n=4 non-uniform-stake scenario
# at the same 20 seeds = 20 metas. Total 120 metas. Each carries the full
# workload axis so the FFG reducer can regenerate the batch stream.
_UNIFORM_NS: tuple[int, ...] = (4, 7, 10, 16, 25)
_SEEDS: tuple[int, ...] = tuple(range(20))


def _meta(run_id: str, n: int, variant: str, seed: int) -> ScenarioMeta:
    return ScenarioMeta(
        run_id=run_id, protocol="casper-ffg", n=n, variant=variant,
        seed=seed, t_max=_T_MAX,
        arrival_process=_ARRIVAL_PROCESS, tx_bytes=_TX_BYTES,
        conflict_rate=_CONFLICT_RATE, offered_rate=_OFFERED_RATE,
        interval=_SLOT_DURATION, slots_per_epoch=_SLOTS_PER_EPOCH,
    )


SCENARIOS: tuple[ScenarioMeta, ...] = tuple(
    [
        _meta(f"casper-ffg-n{n}-uniform", n, "uniform", seed)
        for n in _UNIFORM_NS
        for seed in _SEEDS
    ]
    + [
        _meta("casper-ffg-n4-nonuniform", 4, "nonuniform", seed)
        for seed in _SEEDS
    ]
)


def run_scenario(meta: ScenarioMeta
                 ) -> tuple[list[EventRecord], RunResult, ScenarioMeta]:
    config = _config(meta.n, meta.variant)
    handle = build_run(config, meta.seed, _factory(meta.n, meta.variant))
    t_max = None if math.isnan(meta.t_max) else meta.t_max
    result, logger = run_to_completion(handle, t_max=t_max)
    return logger.records, result, meta
